trigger:
- none

pool:
  vmImage: 'windows-latest'

stages:
- stage: Stage1
  displayName: "Stage 1 - Sleep for 5 minutes"
  jobs:
  - job: SleepJob1
    displayName: "Job 1 - Sleep"
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          sleep 300

- stage: Stage2
  displayName: "Stage 2 - Sleep for 5 minutes"
  dependsOn: Stage1
  jobs:
  - job: SleepJob2
    displayName: "Job 2 - Sleep"
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          sleep 300

