trigger: none

pr: 
  branches:
    include:
    - main
    exclude:
    - '*'
  paths:
    include:
    - test/amol
resources: 
  repositories: 
  - repository: very
    type: GitHub
    name: Test
    connection: Github

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

