resources:
  repositories:
  - repository:   # identifier (A-Z, a-z, 0-9, and underscore)
    type: github  # see the following "Type" topic
    name: Test  # repository name (format depends on `type`)
#    ref: refs/heads/main  # ref name to use; defaults to 'refs/heads/main'
    endpoint: githubconnection  # name of the service connection to use (for types that aren't Azure Repos)
    trigger: none # CI trigger for this repository, no CI trigger if skipped (only works for Azure Repos)
    pr: 
      branches:
        include: 
        - main # branch names which trigger a build
#        exclude: [ string ] # branch names which won't
#      tags:
#        include: [ string ] # tag names which trigger a build
#        exclude: [ string ] # tag names which won't
      paths:
        include: 
        - test/amol/* # file paths which must match to trigger a build
#        exclude: [ string ] # file paths which won't trigger a build
        

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
