trigger:
- main

pool:
  vmImage: windows-latest

stages:
  - stage: Stage1
    jobs:
      - job: Job1
        steps:
          
          - task: CmdLine@2
            inputs:
              script: |
                echo "Running Stage 1"
                timeout /t 300 /nobreak  # Sleeps for 5 minutes (300 seconds)

  - stage: Stage2
    dependsOn: Stage1
    jobs:
      - job: Job2
        steps:
          
          - task: CmdLine@2
            inputs:
              script: |
                echo "Running Stage 2"
                timeout /t 300 /nobreak  # Sleeps for 5 minutes (300 seconds)

