trigger:
- main

pool:
  vmImage: windows-latest

stages:
  - stage: Stage1
    jobs:
      - job: Job1
        steps:
          
          - task: CmdLine@2
            inputs:
              script: |
                sleep 300

  - stage: Stage2
    dependsOn: Stage1
    jobs:
      - job: Job2
        steps:
          
          - task: CmdLine@2
            inputs:
              script: |
                sleep 300

