resources:
  repositories:
  - repository: self
    name: test
    type: github
#    ref: refs/heads/main
    endpoint: mahaleamol777
    trigger: 
       - main
     
    pr: 
      branches:
       include: 
       - main
      paths: 
       include: 
       - test/amol/*

jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: CmdLine@2
    displayName: Command Line Script
