resources:
  repositories:
  - repository: test
    type: GitHub
    connection: github
#    source: 
    pr:
      branches:
        include:
        - main/*
      paths:
        include:
        - amol/*
pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

