trigger: 
- main

pr: 
  branches:
    include:
    - main
    exclude:
    - '*'
  paths:
    include:
    - test/amol

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

