resources:
  repositories:
  - repository: test
    type: github
    endpoint: github
    trigger: none
    pr:
      branches:
        include: 
        - main
      # paths:
      #   include: 
      #   - amol/*

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

